### ISSUE TITLE
Archive fails: GoogleMobileAds.framework does not support the minimum OS Version specified in the Info.plist

### ISSUE THREAD

**Issue by aoverholtzer** [googleads/swift-package-manager-google-mobile-ads#62] opened 2024-03-04 21:39 UTC
### Description

Archiving our app using Xcode 15.3 RC via Xcode Cloud fails the validation stage on App Store Connect due to problems with the framework's Info.plist file. App is targeting iOS and has a deployment target of iOS 15.

The same issue has been reported in two related projects: GoogleAppMeasurement (https://github.com/google/GoogleAppMeasurement/issues/62) and Firebase (https://github.com/firebase/firebase-ios-sdk/issues/12441).

### Reproducing the issue

Archive an app that uses the GoogleMobileAds using Xcode 15.3 RC. Submit it to App Store Connect.

### GoogleMobileAds SDK Version

11.0.1

### Xcode Version

15.3 RC

### Installation Method

Swift Package Manager

### Targeted Platforms

iOS

### Relevant Log Output

`Invalid Bundle. The bundle MyApp.app/Frameworks/GoogleMobileAds.framework does not support the minimum OS Version specified in the Info.plist.`
`Invalid Bundle. The bundle MyApp.app/Frameworks/UserMessagingPlatform.framework does not support the minimum OS Version specified in the Info.plist.`

### Workaround

Archiving with Xcode 15.2 works fine. You can set the Xcode version for Xcode Cloud builds within App Store Connect -> Xcode Cloud -> Manage Workflows -> Workflow -> Xcode version. The default value is "Latest Release".

**Comment by malandr2** [comment] 2024-03-05 15:53
Hey @aoverholtzer, thanks for flagging. This is something we are aware of and will be addressed in the next release. In the meantime, continue using Xcode 15.2.

**Comment by malandr2** [comment] 2024-03-05 23:40
To update my previous response, it is determined that the .plist error is something that Apple has to resolve. They are aware of this error but we do not know when they will address it. 

For now SPM can't use Xcode 15.3, continue using Xcode 15.2 or earlier.

**Comment by yishair-investing** [comment] 2024-03-06 04:53
@malandr2 this issue was fixed on the other Google SDKS, e.g. Firebase [https://github.com/firebase/firebase-ios-sdk/pull/12439](Firebase PR) why is it different for this SDK?

**Comment by zeusent** [comment] 2024-03-06 09:46
I'm having the same issue and it's blocking my development. Any news about this being fixed soon?

**Comment by malandr2** [comment] 2024-03-06 16:07
@yishair-investing 

https://github.com/firebase/firebase-ios-sdk/pull/12439/files#diff-f4eb4ff5ec89af999cbe8fa3ffe5647d7853ffbc9c1515b337ca043c684b6bb4R679 updated the `minimumOSVersion` to `100` which is a workaround for the time being for Xcode 15.3 to be useable with SPM. To truly solve the issue Apple will have to fix. 

And @jamiehunt Apple feedback tickets are internal to them so they cannot be shared.

**Comment by yishair-investing** [comment] 2024-03-06 17:09
@malandr2, a workaround sounds good until Apple can solve the issue properly. Not supporting the latest Xcode/Swift is a big issue. E.g. whats the plan if Apple don't fix this before iOS 18, will Google Ads not support iOS 18?

**Comment by malandr2** [comment] 2024-03-06 21:38
@all 

We expect to have a new Google Mobile Ads version next week that support Xcode 15.3 using the workaround.

**Comment by Ankooo12** [comment] 2024-03-08 11:24
@aoverholtzer 
I was facing the same problem. I just transferred the swift-package-manager to Pods. The issue is solved for me so you can do so.

**Comment by c7topher** [comment] 2024-03-09 02:16
No fix here yet? Sad. Firebase had this fixed so fast.

**Comment by Ankooo12** [comment] 2024-03-09 02:44
Clean Build
Update dependency - 10.22.1
Then try.

If not works. Delete DerivedData, restart Mac and try. It will work

**Comment by c7topher** [comment] 2024-03-09 02:53
> Clean Build Update dependency - Firebase - 10.22.1 Then try. If not works. Delete DerivedData, restart Mac and try. It will work. I have updated 3 apps yesterday with same method so please try.
> […](#)
> On 09-Mar-2024, at 7:47 AM, Chris White ***@***.***> wrote: Firebase

irebase is working fine, its google mobile ads and google user messaging platform that are not working. All the firebase dependencies are working since the fix yesterday

**Comment by VardyNg** [comment] 2024-03-09 03:05
> @ALL
> 
> We expect to have a new Google Mobile Ads version next week that support Xcode 15.3 using the workaround.
> 
> Edit: Apple will still need to fix this issue and it's possible their fix may affect the workaround. After it's been resolved we will revert the workaround in a future release.

Hope it releases soon! Thanks

**Comment by jakirseu** [comment] 2024-03-09 14:32
I am facing same issue in Xcode 15.3.

**Comment by houmie** [comment] 2024-03-09 15:32
> @yishair-investing
> 
> https://github.com/firebase/firebase-ios-sdk/pull/12439/files#diff-f4eb4ff5ec89af999cbe8fa3ffe5647d7853ffbc9c1515b337ca043c684b6bb4R679 updated the `minimumOSVersion` to `100` which is a workaround for the time being for Xcode 15.3 to be useable with SPM. To truly solve the issue Apple will have to fix.

Sorry, is there a way to apply this workaround so I don't have to downgrade Xcode?  Which file do I have to edit?  
Thanks in advance

**Comment by jooyoungho** [comment] 2024-03-10 08:28
While the issue appears to have been resolved for most SDKs in Firebase, GoogleMobileAds and UserMessagingPlatform still throw an Invalid Bundle error 🥲

**Comment by jakirseu** [comment] 2024-03-10 16:04
I have used older Xcode (15.2) and able to upload the app.

**Comment by umutturemen1496** [comment] 2024-03-11 13:22
Please fix the problem. I don't want to downgrade to XCode 15.2 for no reason. This makes no sense.

I am using the main branch to get the most updated version as soon as possible. Nothing has changed since 3 days. Either Apple or you should fix this quickly. We cannot send an update.

![Screenshot 2024-03-11 at 14 22 30](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/83616491/cab8f0c0-a68c-4c16-b0f9-2a7f3e838251)

**Comment by houmie** [comment] 2024-03-11 14:13
Are you sure you haven't mistakenly opened the latest Xcode? This happens to me every time. Make sure you have opened the Xcode in your Downloads folder.

Then fetch the latest packages via SPM.  Clear the Derived Data and try again. It has to work. The error is on your side.

**Comment by malandr2** [comment] 2024-03-11 14:56
@all

We are still on track to release a new version of the Google Mobile Ads SDK (and UMP SDK) that supports Xcode 15.3 later this week.

**Comment by alexsereno** [comment] 2024-03-11 16:26
Here's a workaround that will work more consistently for the time being, if like me you need to release asap.
This also is necessary for Xcode cloud

1. Use XCodes.app to install 15.2 & the correct simulators
2. Using XCodes.app, make 15.2 the active install (checkmark)
3. Open XCode & clear out the build folder, then select file > reset package caches

Once that finishes, you can now push to XCCloud or make an archive. The important step here for Xcode cloud is that your package.resolved file is made from 15.2

**Comment by Horse888** [comment] 2024-03-12 14:25
> @ALL
> 
> We are still on track to release a new version of the Google Mobile Ads SDK (and UMP SDK) that supports Xcode 15.3 later this week.

Also update the framework `UserMessagingPlatform.framework` pls!
```
Asset validation failed
Invalid Bundle. The bundle xxxmeworks/UserMessagingPlatform.framework does not support the minimum OS Version specified in the Info.plist.
```

**Comment by alexsereno** [comment] 2024-03-12 14:46
> > Here's a workaround that will work more consistently for the time being, if like me you need to release asap. This also is necessary for Xcode cloud
> > 
> > 1. Use [XCodes.app](https://github.com/XcodesOrg/XcodesApp) to install 15.2 & the correct simulators
> > 2. Using XCodes.app, make 15.2 the active install (checkmark)
> > 3. Delete the Package.resolved file in your build folder (The Package.resolved file is inside your .xcodeproj directory at [appName].xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved)
> > 4. Open XCode & clear out the build folder, then select file > reset package caches
> > 
> > Once that finishes, you can now push to XCCloud or make an archive. The important step here for Xcode cloud is that your package.resolved file is made from 15.2
> 
> More consistently than what? Its the exact same as the other workaround...

Taking this in good faith - Carefully note the differences in steps. If you don't remove the package.resolved file before you rebuild it with 15.2 XcCloud won't accept the binary, and using XCodes.app allows you to switch releases back and forth much easier. Hope this helps

**Comment by iharkatkavets** [comment] 2024-03-13 21:25
Faced with the same issue using Xcode 15.2. It happened because I installed updated `Command Line Tools` version.
I was able to solve it by toggling `Command Line Tools` to Xcode 15.2

To change `Command Line Tools` Xcode version do the next navigation:
`Settings` (CMD+,) -> `Locations` -> `Command Line Tools` -> Select `Xcode 15.2 (15C500b)`

<img width="415" alt="image" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/1083951/5dbab320-30ad-4f31-be59-f2b270954dfe">
<img width="338" alt="Screenshot 2024-03-13 at 22 24 54" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/1083951/aec84a7d-c2fc-45db-b5f2-826693fcd423">

**Comment by iharkatkavets** [comment] 2024-03-13 21:38
The issue happens at the step of uploading the build to TestFlight. Switching to `Xcode 15.2` with changing `Command Line Tools` version didn't help me.

**Comment by BasilArackal** [comment] 2024-03-14 05:57
> The issue happens at the step of uploading the build to TestFlight. Switching to `Xcode 15.2` with changing `Command Line Tools` version didn't help me.

For me it's showing also when trying to install to a real device, awaiting the fix.

**Comment by icedice** [comment] 2024-03-14 07:54
> The issue happens at the step of uploading the build to TestFlight. Switching to `Xcode 15.2` with changing `Command Line Tools` version didn't help me.

Remember to delete package.resolved after making the switch..

**Comment by malandr2** [comment] 2024-03-14 21:38
@all 

We have just released SPM version 11.2.0 which should address the 15.3 Xcode issue. Please report back the issue still persists. Thanks!

**Comment by jamiehunt** [comment] 2024-03-14 21:44
@malandr2 looks good from my end. Using Xcode 15.3 (latest), updated Swift PM packages to bring in GoogleMobileAds-11.2.0, can produce an archive of my project & upload thru App Store connect successfully. 

Thanks for getting us the workaround in place & hopefully Apple gets root-cause addressed shortly.

**Comment by Daggerpov** [comment] 2024-03-14 22:01
For those who didn't know how to update the package (like me): 

1. Right click on both of the packages (GoogleMobileAds & GoogleUserMessagingPlatform) -> Update Package for both

<img width="327" alt="image" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/53918934/cb1b8527-a5ce-485c-898b-96d8a5baa4d9">
<img width="406" alt="image" src="https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/53918934/f02662a2-99d5-421d-821d-869933eeb63a">

**Comment by jamiehunt** [comment] 2024-03-14 22:03
@Daggerpov - if you want to update all packages at once File -> Packages -> Update to Latest Package Versions 😀

**Comment by yusufonderd** [comment] 2024-03-14 22:06
It was solved with version 11.2.0. Thanks.

**Comment by YuutaEndo** [comment] 2024-03-15 04:51
GoogleMobileAds 11.2.0
GoogleUserMessagingPlatform 2.3.0

With this combination, you can upload your archive to app store connect.
The build should also pass.
Thank you for the information.

**Comment by YuutaEndo** [comment] 2024-03-15 11:09
I have compiled a workaround

https://www.fksystem-wind.com/post/failed-to-load-info-plist-from-bundle-at-path-%E3%81%8C%E3%83%93%E3%83%AB%E3%83%89%E3%82%92%E5%A6%A8%E3%81%92%E3%82%8B?referral=business-feed

**Closed** 2024-03-15 13:48 UTC

**Comment by DiNerdyYawdie** [comment] 2024-10-10 20:09
> @ALL
> 
> Closing this out as the the issue has been resolved. For others who stumble upon this, use Google Mobile Ads SDK 11.2.0 (and UMP SDK 2.3.0) for Xcode 15.3 compatibility. Stay tuned for any updates from Apple. Thanks!

The link for UMP SDK is https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git
